### ISSUE TITLE
FHIR server test environment

### ISSUE THREAD

**Issue by malakhovks** [ylboerner/Einthoven#1]
Hey!
I want try to test your project.
Is it suitable to use [SMART Dev Sandbox](https://github.com/smart-on-fhir/smart-dev-sandbox) as a FHIR server test environment?
If No, can you advise me what to use as a FHIR server test environment.

**Comment by ylboerner** [comment]
Hi @malakhovks, yes, any FHIR endpoint should work with this app. However, you might need to adjust the code a bit to support SMART on FHIR. Checkout this project for further information: https://github.com/smart-on-fhir/Swift-SMART
